apiVersion: v1
kind: ReplicationController
metadata:
  name: backend-contr
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: graphviz
    tier: backend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: graphviz
        tier: backend
    spec:
      containers:
      - name: server
        # Uncomment this line to use the public docker hub image
        #image: omerio/graphviz-server
        # my own private Container Registry image
        image: gcr.io/gdg-apps-1090/graphviz-server
        # Arguments to the image entrypoint
        args: ["8080"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
