apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: graphviz
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: graphviz
    tier: frontend
